### PR TITLE
Support cube:dimensions and overriding of colormap/expression

### PR DESCRIPTION
**Pull request by jverrydt**
For static datasets, we use the cube:dimensions STAC collection config to store the available time dimensions. So, if this time dimension is available, use this to build the capabilities document instead of start- and enddate of the collection.

Also added ability to override some titiler parameters like expression, colormap and color_formula so if you pass them as query parameters, they will have precedence on the config from STAC.

Small EPSG identifier fix in capabilities.

### CODE REVIEW

**Comment by jverrydt** [comment]
@vincentsarago When can we expect this PR to be reviewed / merged? We need this time dimension feature to proceed to an operational environment.

**Review by vincentsarago — APPROVED** [review]

**Comment by vincentsarago** [comment]
@jverrydt the overall looks great, it would be nice to have tests written for this before we merge 🙏

**Comment by jverrydt** [comment]
Great, I'll have a look to add some tests by the end of this week.

**Comment by jverrydt** [comment]
There was some delay due to holiday period but I finally managed to add some additional tests :-)

**Review by vincentsarago — APPROVED** [review]

**Comment by jverrydt** [comment]
When can we plan a release for this?

**Comment by vincentsarago** [comment]
working on this today @jverrydt

**Pull request merged**
